# This is a basic workflow that is manually triggered

name: Publish Package

on:
  workflow_dispatch:
  
env:
    GH_TOKEN: ${{ github.token }}
    
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Get release url
        id: get_release_url
        run: gh release view --json url
      - name: Echo url
        run: echo "${{fromJson(steps.get_release_url.outputs.url)}}"
