# This is a basic workflow that is manually triggered

name: Publish Package

on:
  workflow_dispatch:
  
env:
    GH_TOKEN: ${{ github.token }}
    
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Get release url
        id: get_release_url
        run:  |
            token=$(gh release view --repo $GITHUB_REPOSITORY --json url)
            echo "AUTH_TOKEN=$token" >> "$GITHUB_ENV"
      - run: echo "$AUTH_TOKEN"
      - name: Echo url
        run: echo "${{fromJson($AUTH_TOKEN.url)}}"
