
name: Publish Package

on:
  workflow_dispatch:
  
env:
    GH_TOKEN: ${{ github.token }}
    
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Get release url
        id: get_release_url
        run:  |
            token=$(gh release view --repo $GITHUB_REPOSITORY --json url)
            echo "RELEASE_URL=$token" >> "$GITHUB_ENV"
      - run: echo "${{ fromJson(env.RELEASE_URL).url }}/module.json"
      
      - name: Publish Module to FoundryVTT Website
        id: publish-to-foundry-website
        uses: cs96and/FoundryVTT-release-package@v1
        with:
          package-token: ${{ secrets.PACKAGE_TOKEN }}
          manifest-url: ${{ fromJson(env.RELEASE_URL).url }}/module.json
          dry-run: true
