# This is a basic workflow that is manually triggered

name: Publish Package

on:
  workflow_dispatch:
    inputs:
      release:
        description: 'Release to publish'
        required: true
        type: string

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Echo
        run: gh release view
